# This is a basic workflow that is manually triggered

name: feature deploy workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch: